# Base image
FROM python:3.9-slim

# Set work directory
WORKDIR /app

# Copy Wave app
COPY . /app/

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Run Wave app (adjust as needed)
CMD ["wave", "run", "app"]